INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('01','HPE',1);
INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('02','CNV',1);
INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('03','IT推進',1);
INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('04','CP',1);
INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('05','BI',1);
INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('06','SP',1);
INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('07','Customer Value',1);
INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('08','事業推進部',1);
INSERT INTO SECTION_MST (SECTION_CD,SECTION_NAME,VALID_FLAG) VALUES ('09','役員',1);