INSERT INTO SUBMIT_REQUEST_4_MST (SUBMIT_REQUEST_4_CD,SUBMIT_REQUEST_4_NAME,VALID_FLAG) VALUES ('01','A変',1);
INSERT INTO SUBMIT_REQUEST_4_MST (SUBMIT_REQUEST_4_CD,SUBMIT_REQUEST_4_NAME,VALID_FLAG) VALUES ('02','B変',1);
