INSERT INTO SUBMIT_REQUEST_3_MST (SUBMIT_REQUEST_3_CD,SUBMIT_REQUEST_3_NAME,VALID_FLAG) VALUES ('01','通院',1);
INSERT INTO SUBMIT_REQUEST_3_MST (SUBMIT_REQUEST_3_CD,SUBMIT_REQUEST_3_NAME,VALID_FLAG) VALUES ('02','電車遅延',1);
