INSERT INTO SUBMIT_REQUEST_2_MST (SUBMIT_REQUEST_2_CD,SUBMIT_REQUEST_2_NAME,VALID_FLAG) VALUES ('01','休出',1);
INSERT INTO SUBMIT_REQUEST_2_MST (SUBMIT_REQUEST_2_CD,SUBMIT_REQUEST_2_NAME,VALID_FLAG) VALUES ('02','振出',1);
INSERT INTO SUBMIT_REQUEST_2_MST (SUBMIT_REQUEST_2_CD,SUBMIT_REQUEST_2_NAME,VALID_FLAG) VALUES ('03','代休',1);
INSERT INTO SUBMIT_REQUEST_2_MST (SUBMIT_REQUEST_2_CD,SUBMIT_REQUEST_2_NAME,VALID_FLAG) VALUES ('04','振休',1);
