/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2013-06-24 08:12:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import keiziban_Cus.*;
import java.util.ArrayList;

public final class keiziban_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=Shift_JIS");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      keiziban_Req.Data appData = null;
      synchronized (application) {
        appData = (keiziban_Req.Data) _jspx_page_context.getAttribute("appData", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (appData == null){
          appData = new keiziban_Req.Data();
          _jspx_page_context.setAttribute("appData", appData, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=Shift_JIS\">\r\n");
      out.write("<title>掲示板</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tline-height: 200%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<FORM METHOD=\"POST\" ACTION=\"Keiziban\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<H1>\r\n");
      out.write("\t\t\t\t<b>掲示板</b>\r\n");
      out.write("\t\t\t</H1>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t\t<div style=\"text-alingn: center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t");

					if (appData.Error) {
				
      out.write("\r\n");
      out.write("\t\t\t\tちゃんと記入してちょ。\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 30%; margin-left: auto; margin-right: auto; text-align: left;\">\r\n");
      out.write("\t\t\t\t\t名前 <INPUT TYPE=\"TEXT\" NAME=\"NAME\" SIZE=\"20\" MAXLENGTH=\"15\"><br>\r\n");
      out.write("\t\t\t\t\t件名 <INPUT TYPE=\"TEXT\" NAME=\"KENMEI\" SIZE=\"40\" MAXLENGTH=\"30\"><br>\r\n");
      out.write("\t\t\t\t    <pre><TEXTAREA NAME=\"KOMENT\" ROWS=\"10\" COLS=\"60\"></TEXTAREA></pre>\r\n");
      out.write("\t\t\t\t    <INPUT TYPE=\"submit\" VALUE=\"投稿\"><br>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<H2>\r\n");
      out.write("\t\t\t\t\t\t<b><font size=\"+2\">メッセージ一覧</font></b>\r\n");
      out.write("\t\t\t\t\t</H2>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t<hr width=\"1500\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (appData.nameData != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					for (int i = appData.nameData.size() - 1; i >= 0; i--) {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<font color=\"#ff0000\">");
      out.print(appData.nameData.get(i));
      out.write("</font>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t");
      out.print(appData.kenmeiData.get(i));
      out.write("<br> &nbsp;&nbsp;");
      out.print(appData.dayData.get(i));
      out.write("&nbsp;&nbsp;&nbsp;No.");
      out.print(appData.numData.get(i));
      out.write("<br>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<pre>");
      out.print(appData.komentData.get(i));
      out.write("</pre>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<hr width=\"1500\">\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</FORM>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
